// <auto-generated/>
#pragma warning disable CS0618
using CleanAspire.Api.Client.Stocks.Dispatch;
using CleanAspire.Api.Client.Stocks.Pagination;
using CleanAspire.Api.Client.Stocks.Receive;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CleanAspire.Api.Client.Stocks
{
    /// <summary>
    /// Builds and executes requests for operations under \stocks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StocksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The dispatch property</summary>
        public global::CleanAspire.Api.Client.Stocks.Dispatch.DispatchRequestBuilder Dispatch
        {
            get => new global::CleanAspire.Api.Client.Stocks.Dispatch.DispatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pagination property</summary>
        public global::CleanAspire.Api.Client.Stocks.Pagination.PaginationRequestBuilder Pagination
        {
            get => new global::CleanAspire.Api.Client.Stocks.Pagination.PaginationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The receive property</summary>
        public global::CleanAspire.Api.Client.Stocks.Receive.ReceiveRequestBuilder Receive
        {
            get => new global::CleanAspire.Api.Client.Stocks.Receive.ReceiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAspire.Api.Client.Stocks.StocksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StocksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stocks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAspire.Api.Client.Stocks.StocksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StocksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stocks", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
