// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CleanAspire.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NullableOfProductCategoryDto
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Electronics")]
        #pragma warning disable CS1591
        Electronics,
        #pragma warning restore CS1591
        [EnumMember(Value = "Furniture")]
        #pragma warning disable CS1591
        Furniture,
        #pragma warning restore CS1591
        [EnumMember(Value = "Clothing")]
        #pragma warning disable CS1591
        Clothing,
        #pragma warning restore CS1591
        [EnumMember(Value = "Food")]
        #pragma warning disable CS1591
        Food,
        #pragma warning restore CS1591
        [EnumMember(Value = "Beverages")]
        #pragma warning disable CS1591
        Beverages,
        #pragma warning restore CS1591
        [EnumMember(Value = "HealthCare")]
        #pragma warning disable CS1591
        HealthCare,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sports")]
        #pragma warning disable CS1591
        Sports,
        #pragma warning restore CS1591
    }
}
