// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CleanAspire.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaginatedResultOfProductDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currentPage property</summary>
        public int? CurrentPage { get; set; }
        /// <summary>The hasNextPage property</summary>
        public bool? HasNextPage { get; set; }
        /// <summary>The hasPreviousPage property</summary>
        public bool? HasPreviousPage { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::CleanAspire.Api.Client.Models.ProductDto>? Items { get; set; }
#nullable restore
#else
        public List<global::CleanAspire.Api.Client.Models.ProductDto> Items { get; set; }
#endif
        /// <summary>The totalItems property</summary>
        public int? TotalItems { get; set; }
        /// <summary>The totalPages property</summary>
        public int? TotalPages { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanAspire.Api.Client.Models.PaginatedResultOfProductDto"/> and sets the default values.
        /// </summary>
        public PaginatedResultOfProductDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CleanAspire.Api.Client.Models.PaginatedResultOfProductDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CleanAspire.Api.Client.Models.PaginatedResultOfProductDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::CleanAspire.Api.Client.Models.PaginatedResultOfProductDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currentPage", n => { CurrentPage = n.GetIntValue(); } },
                { "hasNextPage", n => { HasNextPage = n.GetBoolValue(); } },
                { "hasPreviousPage", n => { HasPreviousPage = n.GetBoolValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::CleanAspire.Api.Client.Models.ProductDto>(global::CleanAspire.Api.Client.Models.ProductDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalItems", n => { TotalItems = n.GetIntValue(); } },
                { "totalPages", n => { TotalPages = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("currentPage", CurrentPage);
            writer.WriteBoolValue("hasNextPage", HasNextPage);
            writer.WriteBoolValue("hasPreviousPage", HasPreviousPage);
            writer.WriteCollectionOfObjectValues<global::CleanAspire.Api.Client.Models.ProductDto>("items", Items);
            writer.WriteIntValue("totalItems", TotalItems);
            writer.WriteIntValue("totalPages", TotalPages);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
